### PR TITLE
Test on Travis CI with Ubuntu Xenial and Python 3.7.

### PR DESCRIPTION
**Pull request by andreif**

### CODE REVIEW

**Comment by andreif** [comment]
`3.8-dev` passes the tests, should we add it as well? or `3.8.0a1` feels too early?

**Comment by lericson** [comment]
Add it, why not!

- Ludvig

**Comment by andreif** [comment]
I managed to run tox only after changing the command to:
```
{toxinidir}/bin/with-memcached python {toxinidir}/bin/runtests.py {posargs:-v tests --with-doctest}
```
Using pyenv, I got all tests pass: 
```
$ pyenv shell tox 2.6.9 3.3.7 3.4.9 3.5.6 3.6.8 3.7.2 3.8-dev
$ tox
  ...
  py26: commands succeeded
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
  py38: commands succeeded
  congratulations :)
```

**Comment by andreif** [comment]
Btw, it would be great to push next release soon, so that #246 gets finally resolved.

**Comment by andreif** [comment]
I haven't managed to make tox running with pypy, but it works fine when I run tests directly (atm only 6.0.0 seems available):

```sh
$ pyenv install pypy3.5-6.0.0
$ pyenv shell pypy3.5-6.0.0
$ pypy3 -m pip install nose
$ pypy3 -m pip install -e .

$ ./bin/with-memcached pypy3 ./bin/runtests.py -v tests --with-doctest
...
Ran 56 tests in 14.092s

OK
```

**Comment by andreif** [comment]
Well, if one forks pyenv, pushes new tag, modifies brew formula and installs from the fork, comes future a bit earlier:

1. edit `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb`:
```rb
  url "https://github.com/andreif/pyenv/archive/1.2.10.tar.gz"
  sha256 "49b287efab80ac7c50c684cc7a0c549599603e37abf6af7cf0f5408b4e961265"
```
2. install future pyenv
```sh
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv
```
3. install pypy
```sh
$ pyenv install pypy3.5-7.0.0

Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:43:14)
[PyPy 7.0.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
```
4. tests pass, pretty fast
```
Ran 51 tests in 9.862s
OK
```

Btw, Travis runs an older version:
```
Python 3.5.3 (3f6eaa010fce, Jan 11 2018, 04:44:35)
[PyPy 5.10.1 with GCC 6.2.0 20160901]
```

**Comment by andreif** [comment]
6.0.0 runs also fast, not sure why it took longer before. CPython 3.7 runs in 10.291s.

**Comment by andreif** [comment]
@lericson Hey, anything on your mind that stopping you from merging it? Just let me know where I need to look.

**Comment by lericson** [comment]
Wow, 10 seconds? I have to look into this more. Good job Andrei! Also hi 😄

**Pull request merged**
