### PR TITLE
Upgrade GitHub Actions and add Python 3.11 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
* https://www.python.org/downloads/release/python-3110/
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases

### CODE REVIEW

**Comment by lericson** [comment]
Hi @cclauss, the actions are not going through and GitHub is not letting me restart them (in fact it seems it broke last time I retried)

**Comment by cclauss** [comment]
My mistake.  I was using `ubuntu-2020` instead of `ubuntu-20.04`.

**Comment by cclauss** [comment]
The alternative would be to drop Python 3.6 which is no longer supported:
* https://devguide.python.org/versions

**Comment by lericson** [comment]
I’m up for that. - LudvigOn 15 Jan 2023, at 12:58, Christian Clauss ***@***.***> wrote:﻿
The alternative would be to drop Python 3.6 which is no longer supported:

https://devguide.python.org/versions

**Comment by cclauss** [comment]
Please re-review.

**Comment by lericson** [comment]
Very nice, one last thing needs to be changed, that is the stated Python version requirement in the documentation (`docs`). I can do it once I have a minute also.

**Review by jugmac00 — APPROVED** [review]

**Review by jugmac00 — COMMENTED** [review]
`python_requires` should be updated, too

**Comment by lericson** [comment]
I guess we could add pypy3 to the claimed support since it is indeed tested, but perhaps as a separate PR so I don't forget to merge for so long.

**Pull request merged**
